spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: lwb990924

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
